[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

# Build optimizations (faster compilation)
optimizer = true
optimizer_runs = 200
via_ir = false

# Test runtime settings (fast local runs)
gas_limit = 9223372036854775807
gas_price = 0
block_gas_limit = 30000000

# Caching and parallelization
cache = true
cache_path = "cache"
force = false

# Fuzzing configuration
[profile.default.fuzz]
runs = 256
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

# See all config options: https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
